In [2]:
#scientists.csv 로드하기
import pandas as pd
scientists = pd.read_csv('../data/scientists.csv')
scientists

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [3]:
print(scientists['Age'].mean())

59.125

In [4]:
scientists[scientists['Age'] > scientists['Age'].mean()]

                   Name        Born        Died  Age     Occupation
1        William Gosset  1876-06-13  1937-10-16   61   Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90          Nurse
3           Marie Curie  1867-11-07  1934-07-04   66        Chemist
7          Johann Gauss  1777-04-30  1855-02-23   77  Mathematician

In [6]:
# 날짜가 문자열로 저장됨
print(scientists['Born'].dtype)
print(scientists['Died'].dtype)

object
object

In [8]:
#시간관련 작업을 할 수 있도록 datetime 자료향으로 변형
born_datetime = pd.to_datetime(scientists['Born'], format = '%Y-%m-%d')
born_datetime

0   1920-07-25
1   1876-06-13
2   1820-05-12
3   1867-11-07
4   1907-05-27
5   1813-03-15
6   1912-06-23
7   1777-04-30
Name: Born, dtype: datetime64[ns]

In [9]:
died_time = pd.to_datetime(scientists['Died'], format = '%Y-%m-%d')
died_time

0   1958-04-16
1   1937-10-16
2   1910-08-13
3   1934-07-04
4   1964-04-14
5   1858-06-16
6   1954-06-07
7   1855-02-23
Name: Died, dtype: datetime64[ns]

In [10]:
scientists.head(n=2)

                Name        Born        Died  Age    Occupation
0  Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1     William Gosset  1876-06-13  1937-10-16   61  Statistician

In [11]:
scientists['born-dt'], scientists['died-dt'] = (born_datetime, died_time)
scientists

,Name,Born,Died,Age,Occupation,born-dt,died-dt
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,1920-07-25,1958-04-16
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,1876-06-13,1937-10-16
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,1820-05-12,1910-08-13
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,1867-11-07,1934-07-04
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,1907-05-27,1964-04-14
5,John Snow,1813-03-15,1858-06-16,45,Physician,1813-03-15,1858-06-16
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,1912-06-23,1954-06-07
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,1777-04-30,1855-02-23

In [12]:
scientists.shape

(8, 7)

In [14]:
scientists['age_days_dt'] = (scientists['died-dt'] - scientists['born-dt'])
scientists

,Name,Born,Died,Age,Occupation,born-dt,died-dt,age_days_dt
0,Rosaline Franklin,1920-07-25,1958-04-16,37,Chemist,1920-07-25,1958-04-16,13779 days
1,William Gosset,1876-06-13,1937-10-16,61,Statistician,1876-06-13,1937-10-16,22404 days
2,Florence Nightingale,1820-05-12,1910-08-13,90,Nurse,1820-05-12,1910-08-13,32964 days
3,Marie Curie,1867-11-07,1934-07-04,66,Chemist,1867-11-07,1934-07-04,24345 days
4,Rachel Carson,1907-05-27,1964-04-14,56,Biologist,1907-05-27,1964-04-14,20777 days
5,John Snow,1813-03-15,1858-06-16,45,Physician,1813-03-15,1858-06-16,16529 days
6,Alan Turing,1912-06-23,1954-06-07,41,Computer Scientist,1912-06-23,1954-06-07,15324 days
7,Johann Gauss,1777-04-30,1855-02-23,77,Mathematician,1777-04-30,1855-02-23,28422 days

## 데이터프레임의 열 삭제하기

In [15]:
scientists.columns

Index(['Name', 'Born', 'Died', 'Age', 'Occupation', 'born-dt', 'died-dt',
       'age_days_dt'],
      dtype='object')

In [17]:
# axis=0 행, axis=1 열을 의미
scientists_dropped = scientists.drop(['Age'], axis = 1)
scientists_dropped.columns

Index(['Name', 'Born', 'Died', 'Occupation', 'born-dt', 'died-dt',
       'age_days_dt'],
      dtype='object')

In [18]:
scientists_dropped.head(2)

,Name,Born,Died,Occupation,born-dt,died-dt,age_days_dt
0,Rosaline Franklin,1920-07-25,1958-04-16,Chemist,1920-07-25,1958-04-16,13779 days
1,William Gosset,1876-06-13,1937-10-16,Statistician,1876-06-13,1937-10-16,22404 days

### 데이터를 피클, csv, tsv 파일로 저장하고 불러오기
### 1. 피클로 저장하기
* 바이너리 형태로 스프레드시트보다 더 작은 용량으로 데이터를 저장
* 오래 보관한다는 의미로 붙여진 이름

In [19]:
names = scientists['Name']
names

0       Rosaline Franklin
1          William Gosset
2    Florence Nightingale
3             Marie Curie
4           Rachel Carson
5               John Snow
6             Alan Turing
7            Johann Gauss
Name: Name, dtype: object

In [22]:
names.to_pickle('../output/scientists_names1.pickle')

In [23]:
result = pd.read_pickle('../output/scientists_names1.pickle')
result

0       Rosaline Franklin
1          William Gosset
2    Florence Nightingale
3             Marie Curie
4           Rachel Carson
5               John Snow
6             Alan Turing
7            Johann Gauss
Name: Name, dtype: object

### 2.csv로 저장
### 3.tsv로 저장

In [24]:
names.to_csv('../output/scientists_names1.csv')

In [26]:
scientists.to_csv('../output/scientists_df.tsv', sep = '\t')

In [27]:
scientists.to_csv('../output/scientists_df_no_index.csv', index=False)

## 퀴즈

In [54]:
import pandas as pd
result = pd.read_csv('../data/01. CCTV_in_Seoul.csv')
result

     기관명    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  2780       1292    430    584    932
1    강동구   773        379     99    155    377
2    강북구   748        369    120    138    204
3    강서구   884        388    258    184     81
4    관악구  1496        846    260    390    613
5    광진구   707        573     78     53    174
6    구로구  1561       1142    173    246    323
7    금천구  1015        674     51    269    354
8    노원구  1265        542     57    451    516
9    도봉구   485        238    159     42    386
10  동대문구  1294       1070     23    198    579
11   동작구  1091        544    341    103    314
12   마포구   574        314    118    169    379
13  서대문구   962        844     50     68    292
14   서초구  1930       1406    157    336    398
15   성동구  1062        730     91    241    265
16   성북구  1464       1009     78    360    204
17   송파구   618        529     21     68    463
18   양천구  2034       1843    142     30    467
19  영등포구   904        495    214    195    373
20   용산구  1624       1368    218    112    398
21   은평구  1873       1138    224    278    468
22   종로구  1002        464    314    211    630
23    중구   671        413    190     72    348
24   중랑구   660        509    121    177    109

In [55]:
result.head(5)

   기관명    소계  2013년도 이전  2014년  2015년  2016년
0  강남구  2780       1292    430    584    932
1  강동구   773        379     99    155    377
2  강북구   748        369    120    138    204
3  강서구   884        388    258    184     81
4  관악구  1496        846    260    390    613

In [56]:
result.tail(3)

    기관명    소계  2013년도 이전  2014년  2015년  2016년
22  종로구  1002        464    314    211    630
23   중구   671        413    190     72    348
24  중랑구   660        509    121    177    109

In [57]:
result.iloc[[7, 10, 20]]

     기관명    소계  2013년도 이전  2014년  2015년  2016년
7    금천구  1015        674     51    269    354
10  동대문구  1294       1070     23    198    579
20   용산구  1624       1368    218    112    398

In [58]:
result.columns

Index(['기관명', '소계', '2013년도 이전', '2014년', '2015년', '2016년'], dtype='object')

In [59]:
result.shape

(25, 6)

In [64]:
cctv_seoul1 = result["기관명"]
cctv_seoul1

0      강남구
1      강동구
2      강북구
3      강서구
4      관악구
5      광진구
6      구로구
7      금천구
8      노원구
9      도봉구
10    동대문구
11     동작구
12     마포구
13    서대문구
14     서초구
15     성동구
16     성북구
17     송파구
18     양천구
19    영등포구
20     용산구
21     은평구
22     종로구
23      중구
24     중랑구
Name: 기관명, dtype: object

In [65]:
type(cctv_seoul1)

pandas.core.series.Series

In [66]:
cctv_seoul2 = result[["기관명", "소계", "2016년"]]
cctv_seoul2

     기관명    소계  2016년
0    강남구  2780    932
1    강동구   773    377
2    강북구   748    204
3    강서구   884     81
4    관악구  1496    613
5    광진구   707    174
6    구로구  1561    323
7    금천구  1015    354
8    노원구  1265    516
9    도봉구   485    386
10  동대문구  1294    579
11   동작구  1091    314
12   마포구   574    379
13  서대문구   962    292
14   서초구  1930    398
15   성동구  1062    265
16   성북구  1464    204
17   송파구   618    463
18   양천구  2034    467
19  영등포구   904    373
20   용산구  1624    398
21   은평구  1873    468
22   종로구  1002    630
23    중구   671    348
24   중랑구   660    109

In [67]:
type(cctv_seoul2)

pandas.core.frame.DataFrame